version: 2
updates:
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: weekly
      time: '01:00'
    open-pull-requests-limit: 10
    reviewers:
      - sonallux
    groups:
      maven-plugins:
        dependency-type: development
      test-dependencies:
        patterns:
          - "org.junit.jupiter:junit-jupiter"
          - "org.mockito:mockito-junit-jupiter"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '02:00'
    reviewers:
      - sonallux
